# Welcome to Jekyll!

title: Joan Bono
email: joan@bono.cat
description: > # this means to ignore newlines until "baseurl:"
   twitter: <a href="https://twitter.com/joan_bono">@joan_bono</a><br>Website: <a href="https://joan_bono.github.io/">joan_bono.github.io</a><br>Company: <a href="http://www.ackcent.com/">Ackcent</a><br><br><img src="https://raw.githubusercontent.com/joanbono/joanbono.github.io/master/images/profile.png" alt="MU"><br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-minimal
